services:
  karakeepbot:
    image: ghcr.io/madh93/karakeepbot:latest
    container_name: karakeepbot
    hostname: karakeepbot
    restart: unless-stopped
    env_file: '.env'

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
