{
 "title": "Fail2ban",
 "description": "Metrics and logs for Fail2ban",
 "tags": [
  "docker",
  "prometheus",
  "loki",
  "fail2ban"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource_prometheus", "label": "Prometheus Data Source", "query": "prometheus" },
   { "name": "datasource_loki", "label": "Loki Data Source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Exporter Status",
   "type": "stat",
   "description": "Returns 1 if the exporter is up and running",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "f2b_up", "legendFormat": "Up" }
   ]
  },
  {
   "title": "Exporter Errors",
   "type": "stat",
   "description": "Count the number of errors since startup by type",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(f2b_errors[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "table",
   "description": "The Fail2ban jails configuration",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "targets": [
    { "expr": "f2b_config_jail_max_retries", "legendFormat": "{{jail}}" },
    { "expr": "f2b_config_jail_ban_time", "legendFormat": "{{jail}}" },
    { "expr": "f2b_config_jail_find_time", "legendFormat": "{{jail}}" }
   ]
  },
  {
   "title": "Bans Logs",
   "type": "logs",
   "description": "Fail2ban bans details",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"fail2ban\"} | pattern \"<date> <time> <f2b_internals> [1]: <level>  [<jail>] <action> <ip>\" | action=\"Ban\" | line_format \"[{{.jail}}] {{.ip}} has been banned!\""
    }
   ]
  },
  {
   "title": "Current Failures",
   "type": "timeseries",
   "description": "Number of current failures per jail",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "f2b_jail_failed_current", "legendFormat": "{{jail}}" }
   ]
  },
  {
   "title": "Current Bans",
   "type": "timeseries",
   "description": "Number of IPs currently banned per jail",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "f2b_jail_banned_current", "legendFormat": "{{jail}}" }
   ]
  },
  {
   "title": "Total Failures",
   "type": "timeseries",
   "description": "Total number of failures since fail2ban startup per jail",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "f2b_jail_failed_total", "legendFormat": "{{jail}}" }
   ]
  },
  {
   "title": "Total Bans",
   "type": "timeseries",
   "description": "Total number of banned IPs since fail2ban startup per jail (includes expired bans)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "f2b_jail_banned_total", "legendFormat": "{{jail}}" }
   ]
  }
 ]
}