services:
  qbittorrent_vpn:
    image: qmcgaw/gluetun:latest
    container_name: qbittorrent_vpn
    hostname: qbittorrent_vpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=$VPN_SERVICE_PROVIDER
      - VPN_TYPE=$VPN_TYPE
      - WIREGUARD_PRIVATE_KEY=$WIREGUARD_PRIVATE_KEY
      - SERVER_COUNTRIES=$SERVER_COUNTRIES
      - PORT_FORWARD_ONLY=$PORT_FORWARD_ONLY
    volumes:
      - $DOCKER_DATA/qbittorrent_vpn/config:/gluetun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    depends_on:
      - qbittorrent_vpn
    network_mode: "service:qbittorrent_vpn"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKER_DATA/qbittorrent/config:/config
      - $DOWNLOADS_DATA:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.rule=Host(`$SUBDOMAIN.$DOMAIN_NAME`)"
      - "traefik.http.routers.qbittorrent.tls.domains[0].main=$DOMAIN_NAME"
      - "traefik.http.routers.qbittorrent.tls.domains[0].sans=*.$DOMAIN_NAME"
      - "traefik.http.routers.qbittorrent.tls.certresolver=letsencrypt"
      - "traefik.http.routers.qbittorrent.middlewares=lan-only,error-pages,oidc-auth,security-headers"

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
