version: "3.9"

services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    hostname: fail2ban
    restart: unless-stopped
    cap_add:
      - net_admin
      - net_raw
    environment:
      - TZ=$TZ
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=30d
      - TELEGRAM_AUTH_TOKEN=$TELEGRAM_AUTH_TOKEN  # Telegram notifications
      - TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID
    volumes:
      - $DOCKER_DATA/fail2ban/data:/data
      - $DOCKER_DATA/fail2ban/run:/var/run/fail2ban # Prometheus exporter
      - ./action.d:/data/action.d:ro
      - ./filter.d:/data/filter.d:ro
      - ./jail.d:/data/jail.d:ro
      - ./scripts:/data/scripts:ro
      - /var/log:/var/log:ro
    network_mode: host

  fail2ban_exporter:
    image: registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:latest
    container_name: fail2ban_exporter
    hostname: fail2ban_exporter
    restart: unless-stopped
    depends_on:
      - fail2ban
    volumes:
      - $DOCKER_DATA/fail2ban/run:/var/run/fail2ban:ro
    ports:
      - 9191:9191

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
