services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    hostname: openwebui
    restart: unless-stopped
    environment:
      - WEBUI_AUTH=false # Disable authentication
      - WEBUI_SECRET_KEY=$WEBUI_SECRET_KEY
      - OLLAMA_BASE_URL=$OLLAMA_BASE_URL
    volumes:
      - $DOCKER_DATA/openwebui/data:/app/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8080"
      - "traefik.http.routers.openwebui.entrypoints=websecure"
      - "traefik.http.routers.openwebui.rule=Host(`$SUBDOMAIN.$DOMAIN_NAME`)"
      - "traefik.http.routers.openwebui.tls.domains[0].main=$DOMAIN_NAME"
      - "traefik.http.routers.openwebui.tls.domains[0].sans=*.$DOMAIN_NAME"
      - "traefik.http.routers.openwebui.tls.certresolver=letsencrypt"
      - "traefik.http.routers.openwebui.middlewares=oidc-auth,error-pages,lan-only,security-headers"

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
