services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    hostname: n8n
    restart: unless-stopped
    environment:
      - TZ=$TZ
    volumes:
      - $DOCKER_DATA/n8n/data:/home/node/.n8n
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.rule=Host(`$SUBDOMAIN.$DOMAIN_NAME`)"
      - "traefik.http.routers.n8n.tls.domains[0].main=$DOMAIN_NAME"
      - "traefik.http.routers.n8n.tls.domains[0].sans=*.$DOMAIN_NAME"
      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
      - "traefik.http.routers.n8n.middlewares=authelia,error-pages,lan-only,security-headers"

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
