services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    hostname: uptimekuma
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKER_DATA/uptimekuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker monitoring
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.uptimekuma.loadbalancer.server.port=3001"
      - "traefik.http.routers.uptimekuma.entrypoints=websecure"
      - "traefik.http.routers.uptimekuma.rule=Host(`$SUBDOMAIN.$DOMAIN_NAME`)"
      - "traefik.http.routers.uptimekuma.tls.domains[0].main=$DOMAIN_NAME"
      - "traefik.http.routers.uptimekuma.tls.domains[0].sans=*.$DOMAIN_NAME"
      - "traefik.http.routers.uptimekuma.tls.certresolver=letsencrypt"
      - "traefik.http.routers.uptimekuma.middlewares=oidc-auth,error-pages,lan-only,security-headers"

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
