version: "3.9"

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    user: $PUID
    volumes:
      - $DOCKER_DATA/monitoring/grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.rule=Host(`$GRAFANA_DOMAIN_NAME`)"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.routers.grafana.middlewares=lan-only,security-headers"

  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    hostname: loki
    restart: unless-stopped
    user: $PUID
    command: --config.file=/etc/loki/loki.yml
    volumes:
      - $DOCKER_DATA/monitoring/loki:/tmp/loki
      - ./loki.yml:/etc/loki/loki.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
      - "traefik.http.routers.loki.entrypoints=websecure"
      - "traefik.http.routers.loki.rule=Host(`$LOKI_DOMAIN_NAME`)"
      - "traefik.http.routers.loki.tls.certresolver=letsencrypt"
      - "traefik.http.routers.loki.middlewares=authelia,lan-only,security-headers"

  promtail:
    image: grafana/promtail:2.6.1
    container_name: promtail
    hostname: promtail
    restart: unless-stopped
    command: --config.file=/etc/promtail/promtail.yml
    ports:
      - 1514:1514 # Syslog Listener
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml:ro
      - /var/log:/var/log:ro  # System Varlogs
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Docker Service Discovery
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.promtail.loadbalancer.server.port=9080"
      - "traefik.http.routers.promtail.entrypoints=websecure"
      - "traefik.http.routers.promtail.rule=Host(`$PROMTAIL_DOMAIN_NAME`)"
      - "traefik.http.routers.promtail.tls.certresolver=letsencrypt"
      - "traefik.http.routers.promtail.middlewares=authelia,lan-only,security-headers"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    user: $PUID
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=30d"
    volumes:
      - $DOCKER_DATA/monitoring/prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.rule=Host(`$PROMETHEUS_DOMAIN_NAME`)"
      - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
      - "traefik.http.routers.prometheus.middlewares=authelia,lan-only,security-headers"

  snmp_exporter:
    image: quay.io/prometheus/snmp-exporter:master
    container_name: snmp_exporter
    hostname: snmp_exporter
    restart: unless-stopped
    user: $PUID
    command: --config.file=/etc/snmp_exporter/snmp.yml
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml
    ports:
      - 9116:9116
    network_mode: host # Required!

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
