scrape_configs:
  - job_name: "nas"
    static_configs:
      - targets:
          - "192.168.1.6"   # Synology NAS IP exposing SNMP metrics
    metrics_path: "/snmp"
    params:
      module: [synology]
    scrape_interval: 30s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.6:9116 # The SNMP exporter's real hostname:port
  - job_name: raspberry_pi
    static_configs:
      - targets:
          - 192.168.1.17:9100
    scrape_interval: 30s
    scrape_timeout: 5s
  - job_name: traefik
    static_configs:
      - targets:
          - traefik:8080
    scrape_interval: 30s
    scrape_timeout: 5s
  - job_name: authelia
    static_configs:
      - targets:
          - authelia:9959
    scrape_interval: 1m
    scrape_timeout: 5s
  - job_name: fail2ban
    static_configs:
      - targets:
          - fail2ban_exporter:9191
    scrape_interval: 1m
    scrape_timeout: 5s
