version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    hostname: mosquitto
    restart: unless-stopped
    environment:
      - TZ=$TZ
    ports:
      - 1883:1883
    volumes:
      - $DOCKER_DATA/mosquitto:/mosquitto
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
