version: "3.9"

services:
  chatwithgpt:
    image: ghcr.io/cogentapps/chat-with-gpt:release
    container_name: chatwithgpt
    hostname: chatwithgpt
    restart: unless-stopped
    environment:
      - TZ=$TZ
    volumes:
      - $DOCKER_DATA/chatwithgpt/data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.chatwithgpt.loadbalancer.server.port=3000"
      - "traefik.http.routers.chatwithgpt.entrypoints=websecure"
      - "traefik.http.routers.chatwithgpt.rule=Host(`$DOMAIN_NAME`)"
      - "traefik.http.routers.chatwithgpt.tls.certresolver=letsencrypt"
      - "traefik.http.routers.chatwithgpt.middlewares=authelia,error-pages,lan-only,security-headers"

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
