services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    hostname: watchtower
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - WATCHTOWER_SCHEDULE=0 0 4 * * ?
      - WATCHTOWER_MONITOR_ONLY=false
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://$TELEGRAM_AUTH_TOKEN@telegram?channels=$TELEGRAM_CHAT_ID&parseMode=HTML
      - WATCHTOWER_NOTIFICATION_SKIP_TITLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
