version: "3.9"

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    hostname: adguard
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - $DOCKER_DATA/adguard/work:/opt/adguardhome/work
      - $DOCKER_DATA/adguard/conf:/opt/adguardhome/conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.adguard.loadbalancer.server.port=80" # 3000 on first boot
      - "traefik.http.routers.adguard.entrypoints=websecure"
      - "traefik.http.routers.adguard.rule=Host(`$DOMAIN_NAME`)"
      - "traefik.http.routers.adguard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.adguard.middlewares=authelia,error-pages,lan-only,security-headers"

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
