version: "3.9"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    privileged: true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - $DOCKER_DATA/jellyfin/config:/config
      - /volume1/media/Movies:/data/movies:ro
      - /volume1/media/Shows:/data/tvshows:ro
      - /volume1/media/LiveTV:/data/livetv:ro
      - /volume1/media/Home:/data/home:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.rule=Host(`$DOMAIN_NAME`)"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jellyfin.middlewares=error-pages,security-headers"

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
