services:
  metube:
    image: alexta69/metube:latest
    container_name: metube
    hostname: metube
    restart: unless-stopped
    user: $PUID:$PGID
    environment:
      - TZ=$TZ
    volumes:
      - $DOWNLOADS_DATA:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"
      - "traefik.http.routers.metube.entrypoints=websecure"
      - "traefik.http.routers.metube.rule=Host(`$SUBDOMAIN.$DOMAIN_NAME`)"
      - "traefik.http.routers.metube.tls.domains[0].main=$DOMAIN_NAME"
      - "traefik.http.routers.metube.tls.domains[0].sans=*.$DOMAIN_NAME"
      - "traefik.http.routers.metube.tls.certresolver=letsencrypt"
      - "traefik.http.routers.metube.middlewares=oidc-auth,error-pages,lan-only,security-headers"

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
