services:
  karakeep_chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: karakeep_chrome
    hostname: karakeep_chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - karakeep

  karakeep_meilisearch:
    image: getmeili/meilisearch:v1.13.3
    container_name: karakeep_meilisearch
    hostname: karakeep_meilisearch
    restart: unless-stopped
    volumes:
      - $DOCKER_DATA/karakeep/meilisearch:/meili_data
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_NO_ANALYTICS=true
    networks:
      - karakeep

  karakeep:
    image: ghcr.io/karakeep-app/karakeep:0.26.0
    container_name: karakeep
    hostname: karakeep
    restart: unless-stopped
    depends_on:
      - karakeep_chrome
      - karakeep_meilisearch
    environment:
      - DATA_DIR=/data
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
      - NEXTAUTH_URL=https://$SUBDOMAIN.$DOMAIN_NAME
      - MEILI_ADDR=http://karakeep_meilisearch:7700
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - BROWSER_WEB_URL=http://karakeep_chrome:9222
      - OPENAI_API_KEY=$OPENAI_API_KEY
      # Configuring different AI Providers: https://docs.karakeep.app/Guides/different-ai-providers/
      # - OPENAI_BASE_URL=https://generativelanguage.googleapis.com/v1beta
      # - INFERENCE_TEXT_MODEL=gemini-2.0-flash
      # - INFERENCE_IMAGE_MODEL=gemini-2.0-flash
    volumes:
      - $DOCKER_DATA/karakeep/data:/data
    networks:
      - default
      - karakeep
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.karakeep.loadbalancer.server.port=3000"
      - "traefik.http.routers.karakeep.entrypoints=websecure"
      - "traefik.http.routers.karakeep.rule=Host(`$SUBDOMAIN.$DOMAIN_NAME`)"
      - "traefik.http.routers.karakeep.tls.domains[0].main=$DOMAIN_NAME"
      - "traefik.http.routers.karakeep.tls.domains[0].sans=*.$DOMAIN_NAME"
      - "traefik.http.routers.karakeep.tls.certresolver=letsencrypt"
      - "traefik.http.routers.karakeep.middlewares=authelia,error-pages,lan-only,security-headers"

networks:
  karakeep:
  default:
    name: $DEFAULT_NETWORK
    external: true
